[versions]
agp = "8.13.1"
fluxRouter = "0.0.3"
#noinspection NewerVersionAvailable
kotlin = "2.0.21"
#noinspection GradleDependency
kotlinxCoroutinesCore = "1.7.3"
ksp = "2.0.21-1.0.28"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
#noinspection GradleDependency
protobufJava = "4.33.2"
recyclerview = "1.3.2"
cardview = "1.0.0"
# 网络库
#noinspection NewerVersionAvailable
okhttp = "4.12.0"
#noinspection NewerVersionAvailable
retrofit = "2.9.0"
# 图片加载
#noinspection NewerVersionAvailable
glide = "4.16.0"
#noinspection NewerVersionAvailable
glide-compiler = "4.16.0"
#noinspection NewerVersionAvailable
glide-ksp = "4.16.0"
# JSON解析
#noinspection NewerVersionAvailable
gson = "2.10.1"
# KV 存储
#noinspection NewerVersionAvailable
mmkv = "1.3.14"

fluxrouter = "0.0.2"
mavencentraluploader = "1.0.10"

aether = "1.0.2"

[libraries]
aether-network-api = { module = "com.kernelflux.mobile:aether-network-api", version.ref = "aether" }
aether-kv-api = { module = "com.kernelflux.mobile:aether-kv-api", version.ref = "aether" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
flux-router-core = { module = "com.kernelflux.mobile:flux-router-core", version.ref = "fluxRouter" }
flux-router-compiler-ksp = { module = "com.kernelflux.mobile:flux-router-compiler-ksp", version.ref = "fluxRouter" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
# 网络
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
# 图片加载
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide-ksp" }
# JSON
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
# KV 存储
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }


#aether sdk
aether-imageloader-api = { group = "com.kernelflux.mobile", name = "aether-imageloader-api", version.ref = "aether" }
aether-imageloader-glide = { group = "com.kernelflux.mobile", name = "aether-imageloader-glide", version.ref = "aether" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
flux-router = { id = "com.kernelflux.fluxrouter", version.ref = "fluxrouter" }
maven-central-uploader = { id = "com.kernelflux.maven.publish", version.ref = "mavencentraluploader" }

